import { defineConfig, devices } from '@playwright/test';
/* global process */

export default defineConfig({
  globalSetup: 'e2e/global-setup.cjs',
  testDir: 'e2e/tests',
  timeout: 30_000,
  expect: { timeout: 5000 },
  fullyParallel: false,
  retries: process.env.CI ? 2 : 1,
  reporter: [['list'], ['html', { outputFolder: 'e2e/report' }]],
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL || process.env.BASE_URL || 'http://localhost:5173',
    headless: true,
    viewport: { width: 1280, height: 800 },
    deviceScaleFactor: 1,
    ignoreHTTPSErrors: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'on-first-retry',
    // Use the pre-seeded storage state generated by global-setup so contexts start
    // with the expected `localStorage` values and avoid timing races.
    storageState: 'e2e/.auth_storage.json',
  },
  webServer: {
    command: 'npm run dev -- --port 5173',
    port: 5173,
    // Allow reusing an existing server in CI and local runs. In CI we now build
    // and start a preview server on port 5174 before Playwright executes; set
    // reuseExistingServer=true to avoid Playwright attempting to spawn a dev
    // server and introduce conflicting servers.
    reuseExistingServer: true,
    timeout: 120000,
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
